import { StyleSheet } from 'react-native';
import { colors } from '@/assets/Theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flex: 1,
        paddingHorizontal: 24,
        justifyContent: 'space-between',
    },
    header: {
        alignItems: 'center',
        marginTop: 60,
    },
    iconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.card,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    title: {
        fontSize: 18,
        fontWeight: '900' as const,
        color: colors.text,
        letterSpacing: 2,
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: colors.primary,
        letterSpacing: 1,
        marginBottom: 16,
    },
    description: {
        fontSize: 16,
        color: colors.mutedText,
        textAlign: 'center',
        lineHeight: 22,
    },
    form: {
        gap: 24,
    },
    label: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.text,
        marginBottom: 2,
    },
    input: {
        backgroundColor: colors.card,
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 18,
        color: colors.text,
        borderWidth: 1,
        borderColor: colors.border,
    },
    button: {
        backgroundColor: colors.primary,
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    buttonDisabled: {
        backgroundColor: colors.border,
        opacity: 0.5,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.background,
        letterSpacing: 1,
    },
    buttonContainer: {
        gap: 16,
        marginBottom: 150,
    },
    primaryButton: {
        backgroundColor: colors.primary,
        paddingVertical: 24,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: 'center',
        gap: 8,
    },
    primaryButtonText: {
        fontSize: 18,
        fontWeight: '800' as const,
        color: colors.background,
        letterSpacing: 1,
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.primary,
        paddingVertical: 24,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: 'center',
        gap: 8,
    },
    secondaryButtonText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.primary,
        letterSpacing: 1,
    },
    buttonSubtext: {
        fontSize: 14,
        color: colors.mutedText,
        textAlign: 'center',
    },
    backButton: {
        alignItems: 'center',
        paddingVertical: 16,
    },
    backButtonText: {
        fontSize: 16,
        color: colors.primary,
        textDecorationLine: 'underline',
    },
    footer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    footerText: {
        fontSize: 12,
        color: colors.disabledText,
        textAlign: 'center',
        lineHeight: 16,
    },
    loginFooter: {
        gap: 16,
        alignItems: 'center',
    },
    forgotPasswordButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
    },
    forgotPasswordText: {
        fontSize: 16,
        color: colors.primary,
        fontWeight: '600' as const,
        textDecorationLine: 'underline',
    },
    resendButton: {
        paddingVertical: 12,
        marginBottom: 16,
    },
    resendButtonText: {
        fontSize: 16,
        color: colors.primary,
        fontWeight: '600' as const,
        textAlign: 'center',
    },
    registrationButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
    },
    registrationButtonText: {
        fontSize: 16,
        color: colors.primary,
        fontWeight: '600' as const,
        textAlign: 'center',
        textDecorationLine: 'underline',
    },
    backFab: {
        position: 'absolute',
        left: 24,
        top: 64,
        padding: 10,
        borderRadius: 9999,
        backgroundColor: 'rgba(255,255,255,0.9)',
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    contentNoScroll: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 16,
        // paddingBottom добавляем динамически через kb + insets.bottom
        justifyContent: 'space-between',
    },
    flex1: { flex: 1 },
    footerBlock: { gap: 10 },
    loginFooterRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
    },
});
