import {StyleSheet} from 'react-native';
import {colors} from '@/assets/Theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800' as const,
        color: colors.text,
        letterSpacing: 1,
    },
    phone: {
        fontSize: 14,
        color: colors.mutedText,
        marginTop: 2,
    },
    logoutButton: {
        padding: 8,
    },
    tabContainer: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        paddingVertical: 16,
        gap: 8,
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 8,
        backgroundColor: colors.surface,
    },
    activeTab: {
        backgroundColor: colors.primary,
    },
    tabText: {
        fontSize: 10,
        fontWeight: '700' as const,
        color: colors.mutedText,
        letterSpacing: 1,
    },
    activeTabText: {
        color: colors.textDark,
        fontSize: 11,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    contentBookingAnalytics: {
        paddingHorizontal: 2,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 32,
    },
    statCard: {
        backgroundColor: colors.surface,
        padding: 20,
        borderRadius: 12,
        width: '47%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    statNumber: {
        fontSize: 18,
        fontWeight: '900' as const,
        color: colors.text,
        marginVertical: 8,
    },
    statLabel: {
        fontSize: 12,
        color: colors.mutedText,
        textAlign: 'center',
    },
    section: {
        marginBottom: 1,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '800' as const,
        color: colors.text,
        marginBottom: 16,
        letterSpacing: 1,
    },
    visitCard: {
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 8,
        marginBottom: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    visitInfo: {
        flex: 1,
    },
    customerName: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.text,
    },
    serviceName: {
        fontSize: 14,
        color: colors.mutedText,
    },
    visitDetails: {
        alignItems: 'flex-end',
    },
    visitTime: {
        fontSize: 14,
        color: colors.mutedText,
    },
    visitAmount: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.primary,
    },
    actionButton: {
        backgroundColor: colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 8,
        gap: 8,
        marginBottom: 12,
    },
    actionButtonText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.textDark,
        letterSpacing: 1,
    },
    actionButtonSecondary: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.primary,
        paddingVertical: 16,
        borderRadius: 8,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    actionButtonSecondaryText: {
        fontSize: 14,
        fontWeight: '800' as const,
        color: colors.primary,
        letterSpacing: 1,
    },
    serviceCard: {
        backgroundColor: colors.surface,
        padding: 20,
        borderRadius: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    servicePrice: {
        fontSize: 14,
        color: colors.primary,
        fontWeight: '600' as const,
        marginTop: 8,
    },
    serviceDescription: {
        fontSize: 14,
        color: colors.mutedText,
        marginTop: 4,
    },
    addServiceButton: {
        backgroundColor: colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 8,
        gap: 8,
    },
    addServiceButtonText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.textDark,
        letterSpacing: 1,
    },
    qrDescription: {
        fontSize: 14,
        color: colors.mutedText,
        marginBottom: 24,
        lineHeight: 20,
    },
    qrContainer: {
        alignItems: 'center',
        backgroundColor: colors.text, // белый блок
        padding: 24,
        borderRadius: 12,
        marginBottom: 24,
    },
    qrLabel: {
        fontSize: 14,
        color: colors.textWhite,
        marginTop: 16,
        fontWeight: '600' as const,
    },
    qrInstructions: {
        backgroundColor: colors.surface,
        padding: 20,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    instructionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.primary,
        marginBottom: 12,
        letterSpacing: 1,
    },
    instructionText: {
        fontSize: 14,
        color: colors.text,
        marginBottom: 8,
        lineHeight: 20,
    },
    detailedStatsGrid: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 24,
    },
    detailedStatCard: {
        flex: 1,
        backgroundColor: colors.surface,
        padding: 20,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    detailedStatNumber: {
        fontSize: 32,
        fontWeight: '900' as const,
        color: colors.primary,
        marginBottom: 8,
    },
    detailedStatLabel: {
        fontSize: 12,
        color: colors.mutedText,
        textAlign: 'center',
    },
    chartPlaceholder: {
        backgroundColor: colors.surface,
        padding: 40,
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: colors.border,
    },
    chartPlaceholderText: {
        fontSize: 18,
        fontWeight: '600' as const,
        color: colors.text,
        marginTop: 16,
        marginBottom: 8,
    },
    chartPlaceholderSubtext: {
        fontSize: 14,
        color: colors.mutedText,
        textAlign: 'center',
    },
    emptyState: {
        backgroundColor: colors.surface,
        padding: 40,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    emptyStateText: {
        fontSize: 16,
        color: colors.mutedText,
    },
    visitDate: {
        fontSize: 12,
        color: colors.disabledText,
        marginTop: 2,
    },
    address: {
        fontSize: 12,
        color: colors.disabledText,
        marginTop: 2,
    },
    trackingHeader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        gap: 8,
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.primary,
        gap: 6,
    },
    filterButtonText: {
        fontSize: 12,
        fontWeight: '700' as const,
        color: colors.primary,
        letterSpacing: 1,
    },
    chevron: {transform: [{rotate: '0deg'}]},
    chevronRotated: {transform: [{rotate: '180deg'}]},
    filtersContainer: {
        backgroundColor: colors.surface,
        paddingVertical: 8,
        paddingHorizontal: 4,
        borderRadius: 12,
        marginBottom: 2,
        borderWidth: 1,
        borderColor: colors.border,
    },
    filterLabel: {
        fontSize: 12,
        fontWeight: '700' as const,
        color: colors.primary,
        marginBottom: 10,
        letterSpacing: 1,
    },
    filterRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 16,
    },
    filterChip: {
        backgroundColor: colors.grayDark,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    filterChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
        color: colors.textWhite,
    },
    filterChipText: {
        fontSize: 12,
        color: colors.textWhite,
        fontWeight: '600' as const,
    },
    filterChipTextActive: {
        color: colors.textWhite,
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.grayDark,
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
        gap: 8,
    },
    dateSelectorText: {
        fontSize: 14,
        color: colors.textWhite,
        fontWeight: '600' as const,
    },
    loadOverview: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 24,
    },
    loadCard: {
        flex: 1,
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    loadNumber: {
        fontSize: 24,
        fontWeight: '900' as const,
        color: colors.text,
        marginVertical: 8,
    },
    loadLabel: {
        fontSize: 12,
        color: colors.mutedText,
        textAlign: 'center',
    },
    subsectionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.text,
        marginBottom: 12,
        letterSpacing: 1,
    },
    hourlyChart: {marginBottom: 24},
    hourlyContainer: {flexDirection: 'row', paddingHorizontal: 8, gap: 12},
    hourColumn: {alignItems: 'center', width: 50},
    hourBar: {
        width: 24,
        height: 100,
        backgroundColor: colors.grayDark,
        borderRadius: 4,
        justifyContent: 'flex-end',
        marginBottom: 8,
        overflow: 'hidden',
    },
    hourBarFill: {
        width: '100%',
        borderRadius: 4,
        minHeight: 2,
    },
    hourLabel: {
        fontSize: 10,
        color: colors.mutedText,
        fontWeight: '600' as const,
        marginBottom: 2,
    },
    hourPercentage: {
        fontSize: 10,
        color: colors.text,
        fontWeight: '700' as const,
    },
    statusGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 24,
    },
    statusCard: {
        backgroundColor: colors.surface,
        padding: 12,
        borderRadius: 8,
        width: '47%',
        borderWidth: 1,
        borderColor: colors.border,
    },
    statusHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    statusTime: {
        fontSize: 12,
        color: colors.text,
        fontWeight: '600' as const,
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusText: {
        fontSize: 14,
        fontWeight: '700' as const,
        marginBottom: 4,
        letterSpacing: 1,
    },
    statusBookings: {
        fontSize: 12,
        color: colors.mutedText,
    },
    bookingCard: {
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 8,
        marginBottom: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    bookingInfo: {flex: 1},
    bookingCustomer: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.text,
    },
    bookingService: {
        fontSize: 14,
        color: colors.mutedText,
        marginTop: 2,
    },
    bookingPhone: {
        fontSize: 12,
        color: colors.disabledText,
        marginTop: 2,
    },
    bookingDetails: {alignItems: 'flex-end', gap: 8},
    bookingTime: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '600' as const,
    },
    bookingStatus: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    bookingStatusText: {
        fontSize: 10,
        fontWeight: '700' as const,
        color: colors.textDark,
        letterSpacing: 1,
    },
    washBaysInfo: {
        fontSize: 12,
        color: colors.primary,
        marginTop: 2,
        fontWeight: '600' as const,
    },
    workingHoursInfo: {
        fontSize: 12,
        color: colors.success,
        marginTop: 2,
        fontWeight: '600' as const,
    },
    hourBarClosed: {
        backgroundColor: colors.card,
        opacity: 0.5,
    },
    closedIndicator: {
        width: '100%',
        height: 4,
        backgroundColor: colors.disabledText,
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: 48,
    },
    hourLabelClosed: {color: colors.disabledText},
    hourPercentageClosed: {color: colors.disabledText},
    statusCardClosed: {opacity: 0.6},
    statusTimeClosed: {color: colors.disabledText},
    statusBookingsClosed: {color: colors.disabledText},

    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    profileIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    headerInfo: {flex: 1},

    modalContainer: {
        flex: 1,
        backgroundColor: colors.background,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '800' as const,
        color: colors.text,
        letterSpacing: 1,
    },
    closeButton: {padding: 8},
    modalContent: {flex: 1, paddingHorizontal: 24},

    profileSection: {
        alignItems: 'center',
        paddingVertical: 32,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        marginBottom: 24,
    },
    profileIconLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        borderWidth: 3,
        borderColor: colors.primary,
    },
    profileName: {
        fontSize: 20,
        fontWeight: '700' as const,
        color: colors.text,
        textAlign: 'center',
    },

    fieldContainer: {marginBottom: 24},
    fieldHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    fieldLabelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    fieldLabel: {
        fontSize: 12,
        fontWeight: '700' as const,
        color: colors.primary,
        letterSpacing: 1,
    },
    editButton: {padding: 4},
    fieldValue: {
        fontSize: 16,
        color: colors.text,
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    editContainer: {gap: 12},
    textInput: {
        fontSize: 16,
        color: colors.text,
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    editActions: {flexDirection: 'row', gap: 12},
    cancelButton: {
        flex: 1,
        backgroundColor: colors.border,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: '700' as const,
        color: colors.text,
        letterSpacing: 1,
    },
    saveButton: {
        flex: 1,
        backgroundColor: colors.primary,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    saveButtonText: {
        fontSize: 14,
        fontWeight: '700' as const,
        color: colors.textDark,
        letterSpacing: 1,
    },

    infoContainer: {
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 8,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    infoTitle: {
        fontSize: 12,
        fontWeight: '700' as const,
        color: colors.primary,
        letterSpacing: 1,
        marginBottom: 8,
    },
    infoValue: {
        fontSize: 16,
        color: colors.text,
    },
    logoutButtonModal: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.danger,
        paddingVertical: 16,
        borderRadius: 8,
        gap: 8,
        marginTop: 24,
        marginBottom: 32,
    },
    logoutButtonModalText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.danger,
        letterSpacing: 1,
    },
    profilePhotoImage: {
        width: '100%',
        height: '100%',
        borderRadius: 40,
    },
    cameraOverlayLarge: {
        position: 'absolute',
        bottom: -4,
        right: -4,
        backgroundColor: colors.primary,
        borderRadius: 16,
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: colors.background,
    },

    additionalSettingsSection: {marginBottom: 24},
    settingsToggleItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.surface,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    settingsToggleInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: 16,
    },
    settingsToggleText: {flex: 1},
    settingsItemSubtext: {
        fontSize: 12,
        color: colors.mutedText,
        marginTop: 2,
    },
    toggleSwitch: {
        width: 44,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.border,
        padding: 2,
        justifyContent: 'center',
    },
    toggleActive: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: colors.primary,
        alignSelf: 'flex-end',
    },
    toggleInactive: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: colors.disabledText,
        alignSelf: 'flex-start',
    },

    helpSection: {marginBottom: 32},
    helpSectionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.text,
        marginBottom: 16,
        letterSpacing: 1,
    },
    helpItem: {
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    helpQuestion: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.text,
        marginBottom: 8,
    },
    helpAnswer: {
        fontSize: 14,
        color: colors.mutedText,
        lineHeight: 20,
    },

    contactSection: {marginBottom: 32},
    contactSectionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.text,
        marginBottom: 16,
        letterSpacing: 1,
    },
    contactItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 12,
        marginBottom: 8,
        gap: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    contactText: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500' as const,
    },

    settingsSectionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.text,
        marginBottom: 16,
        letterSpacing: 1,
    },
    settingsItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 12,
        marginBottom: 8,
        gap: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    settingsItemText: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500' as const,
    },
    settingsSection: {marginBottom: 32},

    navbar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: colors.background,
        borderTopColor: colors.border,
        borderTopWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        paddingTop: 8,
    },
    navItem: {
        flex: 1,
        alignItems: 'center',
        gap: 4,
        paddingVertical: 8,
    },
    navLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.secondaryText,
    },
    navLabelActive: {
        color: colors.primary,
    },

    blockTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 8,
    },
    primaryBtn: {
        backgroundColor: colors.primary,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        alignSelf: 'flex-start',
        textAlign: 'center'
    },
    primaryBtnText: {
        color: colors.textWhite,
        fontWeight: '800',
        textAlign: 'center'
    },
    downloadBtnText: {
        width: "100%",
        color: colors.textWhite,
        fontWeight: '800',
        textAlign: 'center',
        paddingVertical: 8
    },
    textWhite: {
        color: colors.textWhite,
    },
    additionBtn: {
        paddingVertical: 4,
    },
    secondaryBtn: {
        borderColor: colors.accent,
        borderWidth: 1,
        borderRadius: 10,
        paddingVertical: 8,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        alignSelf: 'flex-start',
    },
    secondaryBtnText: {
        color: colors.textWhite,
        fontWeight: '700',
    },
    excelSecondaryBtnText: {
        color: colors.accent,
    },
    secondaryBtnTextPrimary: {
        color: colors.text,
        fontWeight: '700',
    },
    rowBetween: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    label: {color: colors.secondaryText, fontSize: 14, fontWeight: '600'},
    value: {color: colors.text, fontSize: 14, maxWidth: '60%'},
    photo: {width: '100%', height: 180, borderRadius: 10, borderWidth: 1, backgroundColor: colors.background},

    counterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        justifyContent: 'center',
    },
    counterBtn: {
        backgroundColor: colors.primary,
        padding: 10,
        borderRadius: 10,
    },
    counterValue: {
        color: colors.text,
        fontSize: 20,
        fontWeight: '800',
        minWidth: 36,
        textAlign: 'center',
    },
    hint: {color: colors.disabledText, marginTop: 8},

    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        justifyContent: 'space-between',
    },
    priceInput: {
        backgroundColor: colors.background,
        borderColor: colors.border,
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 8,
        color: colors.text,
        minWidth: 110,
        textAlign: 'right',
    },

    input: {
        backgroundColor: colors.background,
        borderColor: colors.border,
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
    },
    customRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    customText: {color: colors.text, fontSize: 14, fontWeight: '600'},

    saveAllBtn: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        marginTop: 4,
        marginBottom: 40,
    },
    saveAllText: {color: colors.textWhite, fontWeight: '900', fontSize: 16},

    mapHeader: {
        paddingTop: 14,
        paddingHorizontal: 16,
        paddingBottom: 12,
        borderBottomColor: colors.border,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    mapHeaderTitle: {color: colors.text, fontSize: 16, fontWeight: '800'},
    mapStub: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 24,
        gap: 16,
    },
    mapStubText: {color: colors.secondaryText, textAlign: 'center'},

    /* ======== SELECT-LIST ======== */
    selectTrigger: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: '#fff',
    },
    selectText: {
        fontSize: 16,
        color: '#14213D',
        flex: 1,
    },

    listContent: {padding: 12},
    listItem: {
        paddingVertical: 14,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        marginBottom: 10,
        backgroundColor: colors.surface,
    },
    listItemActive: {
        borderColor: colors.primary,
    },
    listItemText: {color: colors.text},

    gap12: {gap: 12},
    gap8: {gap: 8},
    mb8: {marginBottom: 8},
    mb0: {
        marginBottom: 0,
    },
    mt8: {marginTop: 8},
    mt30: {
        marginTop: 30
    },
    rowCenterGap12: {
        flexDirection: 'row',
        alignItems: 'center',

        gap: 12,
    },
    flex1: {flex: 1},
    adminScrollContent: {padding: 16, paddingBottom: 140},
    qrScrollContent: {padding: 16, paddingBottom: 120},
    mapWebView: {flex: 1, backgroundColor: colors.background},
    primaryBtnWide: {
        alignSelf: 'stretch',
        width: '100%',
        marginBottom: 12,
        textAlign: 'center',
    },
    primaryBtnThird: {
        alignSelf: 'stretch',
        width: '32%',
        marginBottom: 12,
        textAlign: 'center',
    },
    segmentContainer: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 8,
        marginBottom: 12,
        paddingHorizontal: 16,
    },
    segmentBtn: {
        flex: 1,
        height: 40,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E0E3E7',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
    },
    segmentBtnActive: {
        backgroundColor: '#14213D',
        borderColor: '#14213D',
    },
    segmentText: {
        fontSize: 14,
        color: '#14213D',
        fontWeight: '600',
    },
    segmentTextActive: {
        color: '#fff',
    },
    headerStrip: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderBottomColor: '#E9ECEF',
        borderBottomWidth: 1,
        backgroundColor: '#fff',
    },
    headerStripInner: {
        alignItems: 'center',
        gap: 8,
    },
    headerChipSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        paddingVertical: 6,
        paddingHorizontal: 10,
        marginRight: 4,
    },
    headerChipSummaryText: {
        fontSize: 12,
        color: '#14213D',
        fontWeight: '600',
    },
    headerChipRefresh: {
        marginLeft: 8,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 10,
        backgroundColor: '#EEF2FF',
    },
    headerChipRefreshText: {
        fontSize: 11,
        color: '#14213D',
        fontWeight: '600',
    },
    headerChipMuted: {
        backgroundColor: '#F9FAFB',
        borderRadius: 12,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    headerChipMutedText: {
        fontSize: 12,
        color: '#6B7280',
    },
    bookingChip: {
        backgroundColor: '#14213D',
        borderRadius: 12,
        paddingVertical: 8,
        paddingHorizontal: 12,
        minWidth: 160,
    },
    bookingChipTime: {
        fontSize: 12,
        color: '#FFD166',
        fontWeight: '700',
    },
    bookingChipMain: {
        fontSize: 13,
        color: '#FFFFFF',
        fontWeight: '600',
        marginTop: 2,
    },
    bookingChipSub: {
        fontSize: 11,
        color: '#D1D5DB',
        marginTop: 2,
    },
    backdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 16,
    },
    card: {
        width: '100%',
        borderRadius: 16,
        backgroundColor: '#fff',
        padding: 16,
    },
    title: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 8,
        color: '#14213D',
    },
    actionsScroll: {
        paddingHorizontal: 16,
        paddingTop: 8,
    },
    actionsContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: 12, // если gap не работает на твоей версии RN — поставь marginRight у детей
    },
    btn: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
    },
    btnGhost: {
        backgroundColor: 'transparent',
    },
    btnPrimary: {
        backgroundColor: '#14213D',
    },
    btnText: {
        fontSize: 14,
        fontWeight: '600',
    },
    btnTextGhost: {
        color: '#14213D',
    },
    btnTextPrimary: {
        color: '#fff',
    },
    checkoutCard: {
        backgroundColor: colors.accent,
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    paymentCard: {
        backgroundColor: colors.accent,
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 12,
    },
    checkoutBlockTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.textDark,
        marginBottom: 12,
    },
    washRow: {flexDirection: 'row', gap: 12, alignItems: 'center', marginBottom: 8},
    washThumb: {width: 48, height: 48, borderRadius: 8, backgroundColor: '#eee'},
    washName: {fontSize: 15, fontWeight: '700', color: colors.textDark},
    washAddress: {fontSize: 12, color: colors.mutedText, marginTop: 2},

    extrasTitle: {fontSize: 14, fontWeight: '600', color: colors.textDark, marginTop: 10, marginBottom: 8},
    mutedText: {color: colors.mutedText, fontSize: 13},

    billingCard: {
        backgroundColor: colors.primary,
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 12,
    },
    billingRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8},
    billingLabel: {fontSize: 14, color: colors.textDark},
    billingValue: {fontSize: 14, color: colors.textDark, fontWeight: '600'},
    billingDivider: {height: 1, backgroundColor: '#EFEFEF', marginVertical: 8},
    billingTotalRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
    billingTotalLabel: {fontSize: 16, fontWeight: '800', color: colors.primary},
    billingTotalValue: {fontSize: 16, fontWeight: '800', color: colors.primary},

    paySelector: {
        flexDirection: 'row',
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        padding: 4,
        gap: 6,
    },
    payOption: {flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center'},
    payOptionActive: {backgroundColor: colors.primary + '22'},
    payOptionActiveDisabled: {backgroundColor: '#eaeaea'},
    payOptionText: {fontSize: 14, color: colors.textDark, fontWeight: '600'},
    payOptionTextActive: {color: colors.primary},

    primaryCTA: {
        backgroundColor: colors.primary,
        paddingVertical: 14,
        borderRadius: 14,
        alignItems: 'center',
    },
    primaryCTAText: {color: colors.textWhite, fontSize: 16, fontWeight: '800'},
    pendingCashText: {textAlign: 'center', color: colors.mutedText, marginTop: 10},


});
