import { StyleSheet } from 'react-native';
import { colors } from '@/assets/Theme/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flex: 1,
        paddingHorizontal: 24,
    },
    header: {
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 32,
    },
    iconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.card,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    title: {
        fontSize: 28,
        fontWeight: '900' as const,
        color: colors.text,
        letterSpacing: 1,
        marginBottom: 8,
        textAlign: 'center',
    },
    description: {
        fontSize: 16,
        color: colors.mutedText,
        textAlign: 'center',
    },
    form: {
        gap: 24,
    },
    formGroup: {
        gap: 8,
    },
    label: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.text,
    },
    input: {
        backgroundColor: colors.card,
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 16,
        color: colors.text,
        borderWidth: 1,
        borderColor: colors.border,
    },
    locationPicker: {
        gap: 12,
    },
    locationButton: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.primary,
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    locationButtonText: {
        fontSize: 14,
        fontWeight: '700' as const,
        color: colors.primary,
        letterSpacing: 1,
    },
    selectedLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 8,
    },
    selectedLocationText: {
        fontSize: 14,
        color: colors.success,
        fontWeight: '600' as const,
    },
    locationHint: {
        fontSize: 12,
        color: colors.grayMedium,
        textAlign: 'center',
        lineHeight: 16,
    },
    footer: {
        paddingVertical: 24,
    },
    button: {
        backgroundColor: colors.primary,
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    buttonDisabled: {
        backgroundColor: colors.border,
        opacity: 0.5,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: colors.background,
        letterSpacing: 1,
    },
    washBaysContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    washBayOption: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: colors.card,
        borderWidth: 2,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    washBayOptionActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    washBayOptionText: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: colors.mutedText,
    },
    washBayOptionTextActive: {
        color: colors.background,
    },
    washBaysHint: {
        fontSize: 12,
        color: colors.grayMedium,
        marginTop: 8,
        lineHeight: 16,
    },
    workingHoursOption: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: colors.border,
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 16,
    },
    workingHoursOptionActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    workingHoursOptionText: {
        fontSize: 14,
        fontWeight: '700' as const,
        color: colors.mutedText,
        letterSpacing: 1,
    },
    workingHoursOptionTextActive: {
        color: colors.background,
    },
    timePickersContainer: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 12,
    },
    timePickerContainer: {
        flex: 1,
        alignItems: 'center',
    },
    timePickerLabel: {
        fontSize: 14,
        fontWeight: '600' as const,
        color: colors.text,
        marginBottom: 12,
        textAlign: 'center',
    },
    timePickerControls: {
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        paddingVertical: 8,
        paddingHorizontal: 16,
        minWidth: 100,
    },
    timePickerButton: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    timePickerDisplay: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: colors.surface,
        borderRadius: 8,
        marginVertical: 4,
        minWidth: 80,
        alignItems: 'center',
    },
    timePickerValue: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: colors.primary,
        textAlign: 'center',
    },
    workingHoursHint: {
        fontSize: 12,
        color: colors.grayMedium,
        lineHeight: 16,
    },
});
